function FeatureType4Value = CalcValuesFeaturesType4Vector(Features,j,Set)
    %subtract upper left rectangle  and lower right rectangle from lower
    %left rectangle  and upper right rectangle
    upperRightRectangleSum =  FetchIIValue(Features{4}(6,j),Set ) - ...
                                                        FetchIIValue(Features{4}(5,j),Set) - ...
                                                        FetchIIValue(Features{4}(3,j),Set) + ...
                                                        FetchIIValue(Features{4}(2,j),Set);
    upperLeftRectangleSum =  FetchIIValue(Features{4}(5,j),Set) - ...
                                                        FetchIIValue(Features{4}(4,j),Set) - ...
                                                        FetchIIValue(Features{4}(2,j),Set) + ...
                                                        FetchIIValue(Features{4}(1,j),Set);
    lowerRightRectangleSum =  FetchIIValue(Features{4}(9,j),Set ) - ...
                                                        FetchIIValue(Features{4}(6,j),Set) - ...
                                                        FetchIIValue(Features{4}(8,j),Set) + ...
                                                        FetchIIValue(Features{4}(5,j),Set);
    lowerLeftRectangleSum =  FetchIIValue(Features{4}(8,j),Set) - ...
                                                        FetchIIValue(Features{4}(5,j),Set) - ...
                                                        FetchIIValue(Features{4}(7,j),Set) + ...
                                                        FetchIIValue(Features{4}(4,j),Set);
    FeatureType4Value = lowerLeftRectangleSum + upperRightRectangleSum - lowerRightRectangleSum - upperLeftRectangleSum;
end