function FeatureType3Value = CalcValuesFeaturesType3Vector(Features,j,Set)
    %subtract left rectangle  and right rectangle from center rectangle
    rightRectangleSum =  FetchIIValue(Features{3}(8,j),Set ) - ...
                                                        FetchIIValue(Features{3}(4,j),Set) - ...
                                                        FetchIIValue(Features{3}(7,j),Set) + ...
                                                        FetchIIValue(Features{3}(3,j),Set);
    leftRectangleSum =  FetchIIValue(Features{3}(6,j),Set) - ...
                                                        FetchIIValue(Features{3}(5,j),Set) - ...
                                                        FetchIIValue(Features{3}(2,j),Set) + ...
                                                        FetchIIValue(Features{3}(1,j),Set);
    centerRectangleSum =  FetchIIValue(Features{3}(7,j),Set) - ...
                                                        FetchIIValue(Features{3}(6,j),Set) - ...
                                                        FetchIIValue(Features{3}(3,j),Set) + ...
                                                        FetchIIValue(Features{3}(2,j),Set);
    FeatureType3Value = centerRectangleSum - rightRectangleSum - leftRectangleSum;
end
