function [FeatureType2Value] = CalcValuesFeaturesType2Vector(Features,j,Set)
    %subtract left rectangle  from right rectangle 
    rightRectangleSum =  FetchIIValue(Features{2}(6,j),Set ) - ...
                                                        FetchIIValue(Features{2}(5,j),Set) - ...
                                                        FetchIIValue(Features{2}(3,j),Set) + ...
                                                        FetchIIValue(Features{2}(2,j),Set);
    leftRectangleSum =  FetchIIValue(Features{2}(5,j),Set) - ...
                                                        FetchIIValue(Features{2}(2,j),Set) - ...
                                                        FetchIIValue(Features{2}(4,j),Set) + ...
                                                        FetchIIValue(Features{2}(1,j),Set);
    FeatureType2Value = rightRectangleSum - leftRectangleSum;
end