function TestCalcValuesFeatures
% load Features;
% nExamples = 10;
% set = zeros(20,20,nExamples);
% set(2:20,11:20,:) = ones(19,10,nExamples);
% set = cumsum(set,1);
% set = cumsum(set,2);

load Features;
nExamples = 10;
set = zeros(20,20,nExamples);
set(2:20,2:20,:) = round(rand(19,19,nExamples)*10);
set = cumsum(set,1);
set = cumsum(set,2);

value1 = CalcValuesFeaturesType1(Features{1}(:,end),set);
value2 = CalcValuesFeaturesType2(Features{2}(:,end),set);
value3 = CalcValuesFeaturesType3(Features{3}(:,end),set);
value4 = CalcValuesFeaturesType4(Features{4}(:,end),set);
end

function value = CalcValuesFeaturesType1(feature,Box)
    %subtract rectangle below from rectangle above
    rectangleAboveSum = FetchIIValue(feature(4),Box) -...
                                                    FetchIIValue(feature(3),Box)-...
                                                    FetchIIValue(feature(2),Box)+...
                                                    FetchIIValue(feature(1),Box);

    rectangleBelowSum = FetchIIValue(feature(6),Box) -...
                                                   FetchIIValue(feature(4),Box)-...
                                                   FetchIIValue(feature(5),Box)+...
                                                   FetchIIValue(feature(3),Box);
    value = rectangleAboveSum - rectangleBelowSum;
end

function value = CalcValuesFeaturesType2(feature,Box)
    %subtract left rectangle  from right rectangle 
    rightRectangleSum =  FetchIIValue(feature(6),Box ) - ...
                                                        FetchIIValue(feature(5),Box) - ...
                                                        FetchIIValue(feature(3),Box) + ...
                                                        FetchIIValue(feature(2),Box);
    leftRectangleSum =  FetchIIValue(feature(5),Box) - ...
                                                        FetchIIValue(feature(2),Box) - ...
                                                        FetchIIValue(feature(4),Box) + ...
                                                        FetchIIValue(feature(1),Box);
    value = rightRectangleSum - leftRectangleSum;
end

function value = CalcValuesFeaturesType3(feature,Box)
   %subtract left rectangle  and right rectangle from center rectangle
    rightRectangleSum =  FetchIIValue(feature(8),Box ) - ...
                                                        FetchIIValue(feature(4),Box) - ...
                                                        FetchIIValue(feature(7),Box) + ...
                                                        FetchIIValue(feature(3),Box);
    leftRectangleSum =  FetchIIValue(feature(6),Box) - ...
                                                        FetchIIValue(feature(5),Box) - ...
                                                        FetchIIValue(feature(2),Box) + ...
                                                        FetchIIValue(feature(1),Box);
    centerRectangleSum =  FetchIIValue(feature(7),Box) - ...
                                                        FetchIIValue(feature(6),Box) - ...
                                                        FetchIIValue(feature(3),Box) + ...
                                                        FetchIIValue(feature(2),Box);
    value = centerRectangleSum - rightRectangleSum - leftRectangleSum;
end

function value = CalcValuesFeaturesType4(feature,Box)
%subtract upper left rectangle  and lower right rectangle from lower
    %left rectangle  and upper right rectangle
    upperRightRectangleSum =  FetchIIValue(feature(6),Box ) - ...
                                                        FetchIIValue(feature(5),Box) - ...
                                                        FetchIIValue(feature(3),Box) + ...
                                                        FetchIIValue(feature(2),Box);
    upperLeftRectangleSum =  FetchIIValue(feature(5),Box) - ...
                                                        FetchIIValue(feature(4),Box) - ...
                                                        FetchIIValue(feature(2),Box) + ...
                                                        FetchIIValue(feature(1),Box);
    lowerRightRectangleSum =  FetchIIValue(feature(9),Box ) - ...
                                                        FetchIIValue(feature(6),Box) - ...
                                                        FetchIIValue(feature(8),Box) + ...
                                                        FetchIIValue(feature(5),Box);
    lowerLeftRectangleSum =  FetchIIValue(feature(8),Box) - ...
                                                        FetchIIValue(feature(5),Box) - ...
                                                        FetchIIValue(feature(7),Box) + ...
                                                        FetchIIValue(feature(4),Box);
    value = lowerLeftRectangleSum + upperRightRectangleSum - lowerRightRectangleSum - upperLeftRectangleSum;
end